blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/novasuitelabs/textmodifiers/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/novasuitelabs/textmodifiers#readme
    about: Please check the documentation first.
